### ISSUE TITLE
Crash due to maximum call stack size exceeded

### ISSUE THREAD

**Issue by EasyXploit** [EasyXploit/HelpBot#84]
**Describe the bug**
The bot crashes for unknown reasons due to a memory leak.

**Error trace**
```js
(node:106078) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
(node:106078) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
node:events:484
EventEmitter.prototype.emit = function emit(type, ...args) {
                                           ^
RangeError: Maximum call stack size exceeded
    at DelayedStream.emit (node:events:484:44)
    at DelayedStream._handleEmit (/home/dperales555/HelpBot/node_modules/delayed-stream/lib/delayed_stream.js:82:15)
    at source.emit (/home/dperales555/HelpBot/node_modules/delayed-stream/lib/delayed_stream.js:29:19)
    at source.emit (/home/dperales555/HelpBot/node_modules/delayed-stream/lib/delayed_stream.js:30:21)
    at source.emit (/home/dperales555/HelpBot/node_modules/delayed-stream/lib/delayed_stream.js:30:21)
    at source.emit (/home/dperales555/HelpBot/node_modules/delayed-stream/lib/delayed_stream.js:30:21)
    at source.emit (/home/dperales555/HelpBot/node_modules/delayed-stream/lib/delayed_stream.js:30:21)
    at source.emit (/home/dperales555/HelpBot/node_modules/delayed-stream/lib/delayed_stream.js:30:21)
    at source.emit (/home/dperales555/HelpBot/node_modules/delayed-stream/lib/delayed_stream.js:30:21)
    at source.emit (/home/dperales555/HelpBot/node_modules/delayed-stream/lib/delayed_stream.js:30:21)

Node.js v18.4.0
```

**Comment by EasyXploit** [comment]
The error has not reappeared in two months of consecutive monitored use, and it has not been able to be reproduced, so this issue will be closed, and reopened if this situation occurs again.
