### ISSUE TITLE
Locale not defined in global function

### ISSUE THREAD

**Issue by EasyXploit** [EasyXploit/HelpBot#86]
**Describe the bug**
During the execution of the global moderation function "checkMessage", an error appears in the console indicating that "locale is not defined" only if a infraction is found in the message and the channel type is "DM".

**Error trace**
```js
9/2/2022, 5:45:49 PM 》ERROR: Promise rejected not handled: ReferenceError: locale is not defined
    at exports.run (/***/***/HelpBot/functions/moderation/checkMessage.js:188:84)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.run (/***/***/HelpBot/handlers/events/messageCreate.js:10:25)
```

**Comment by EasyXploit** [comment]
Fixed in https://github.com/EasyXploit/HelpBot/issues/86.
